services:
  web:
    build:
      context: .
    container_name: rails_app
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    depends_on:
      - db
      - redis
      - sidekiq
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/myapp_development
      REDIS_URL: redis://redis:6379/1
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    networks:
      - myapp_network

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_development
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - myapp_network

  redis:
    image: redis:7.0.15
    container_name: redis_cache
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - myapp_network

  sidekiq:
    build: .
    container_name: sidekiq_worker
    depends_on:
      - redis
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/myapp_development
      REDIS_URL: redis://redis:6379/1
    command: bundle exec sidekiq
    volumes:
      - .:/app
    networks:
      - myapp_network

volumes:
  postgres_data:
  redis_data:

networks:
  myapp_network: